
data:
  wav: ./dataset
  samplerate: 48000
  segment: 8
  shift: 1
  channels: 2
  normalize: true
  metadata: ./metadata
  sources: ['bass', 'drums', 'other', 'vocals']

ema:
  epoch: [0.9, 0.95]
  batch: [0.9995, 0.9999]

model:
  sources: ['bass', 'drums', 'other', 'vocals']
  audio_channels: 2
  dims: [4, 32, 64, 128]
  nfft: 4096
  hop_size: 1024
  win_size: 4096
  normalized: True
  band_SR: [0.175, 0.392, 0.433]
  band_stride: [1, 4, 16]
  band_kernel: [3, 4, 16]
  conv_depths: [3,2,1]
  compress: 4
  conv_kernel: 3
  num_dplayer: 6
  expand: 2
  d_state: 64
  d_conv: 4
  dt_rank: "auto"
  dt_min: 0.001
  dt_max: 0.1

epochs: 100000
batch_size: 8

optim:
  lr: 0.0005
  decay_rate: 0.98
  decay_step: 10
  momentum: 0.9
  beta2: 0.999
  optim: adam
  weight_decay: 0

seed: 42
save_every: 1

augment:
  shift_same: false
  remix:
    proba: 1
    group_size: 4
  scale:
    proba: 1
    min: 0.25
    max: 1.25
  flip: true

misc:
  num_workers: 0
